[project]
name = "demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bcrypt>=4.3.0",
    "duckdb>=1.3.2",
    "pandas>=2.3.1",
    "streamlit>=1.47.0",
]
